[package]
name = "koda"
version = "0.1.0"
authors = ["Eli Adelhult <hello@eli.nu>"]
edition = "2018"
build = "build.rs"

[dependencies]
logos = "0.11.4"
rlua = "0.17.0"
regex = "1.3.7"
open = "1.4.0"
rustyline = "6.3.0"
colored = "2"

[build-dependencies]
winres = "0.1"